name: Test the Lab 2 of Testing
on: push
jobs:
  test-testing-lab2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - id: simple-run
        uses: ./.
        with:
          addition-input-1: 4
          addition-input-2: 5
          palindrome-input: "kayak"

      # Test 1
      - name: Test addition
        id: addition
        uses: ./.
        with:
          addition-input-1: 4
          addition-input-2: 5
      - name: Validate // Test addition
        run: |
          [[ "${{ steps.addition.outputs.outputAdditionValue }}" -eq 9 ]]


