name: Test the Lab 1 of code
on: push
jobs:
  test-syntax-lab1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: default run
        uses: ./.

      - name: custom run with mandatory input
        uses: ./.
        with:
          say: GitHub Action Rocks

      - name: custom run with all inputs
        uses: ./.
        with:
          say: GitHub Action Rocks
          eyes: o-